### ISSUE TITLE
sample model Fox doesn't work

### ISSUE THREAD

**Issue by daose** [ProtoArt/spritec#211]
thread 'main' panicked at 'Unable to read index buffer from glTF geometry', src/libcore/option.rs:1188:5

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox

**Comment by sunjay** [comment]
I looked into this more. If a model doesn't have an index buffer, we're supposed to use its triangles as-is. That is, we're supposed to treat every 3 positions as a triangle, rather than having them all deduplicated. 

To fix this bug, we would need to somehow convert meshes without index buffers into a mesh with an index buffer. This is technically possible, but not high priority, so I am closing this for now.

It's easy to workaround this issue by importing the model into Blender and re-exporting it.

![fox](https://user-images.githubusercontent.com/530939/76793545-9542db80-679b-11ea-9285-100120b63bf9.png)
