### ISSUE TITLE
sprites look different after #58

### ISSUE THREAD

**Issue by daose** [ProtoArt/spritec#75]
After #58, it seems that the sprites look different. Is this because the angle is different or did something break?

fyi: @marauder00 @sunjay 

before (f85ff5819165c181e55e7fe8e52177ae3f167a8d):
![pre-pose000001](https://user-images.githubusercontent.com/15278132/63694533-3cd0de80-c849-11e9-9b50-54a771bc4909.png)

after (c56e7dc72239d2851ec4f22de633ea95f6c00dee):
![pose000001](https://user-images.githubusercontent.com/15278132/63694538-41959280-c849-11e9-9a14-07173ad362ac.png)

**Comment by sunjay** [comment]
This is expected behavior. We no longer have fake "good" angles that are tailored specifically for bigboi. We should fix this by changing the bigboi config file to list camera angles that look similar to what we had before. (or by changing the 3D model to look better at this angle)

Thanks for bringing it up!

**Comment by daose** [comment]
Ah if it's expected for now I'll close it then. Thanks for confirming!

**Comment by sunjay** [comment]
I actually think we should keep this open so we can fix our config or the 3D model. Bigboi is our main test model and he should look good. Thanks for bringing it up! 😊

**Comment by sunjay** [comment]
I'm going to fix this once we have camera support.

**Comment by sunjay** [comment]
This was fixed in https://github.com/ProtoArt/spritec/pull/152 I just forgot to close the issue.
